### ISSUE TITLE
A good thought...but...

### ISSUE THREAD

**Issue by driskerr** [pvcousin/sql-scratch-capstone-turn-in#1]
https://github.com/pvcousin/sql-scratch-capstone-turn-in/blob/ea224748dad4b1e8b4a7bdd3c70ae0c5a259135f/SQL%20Project%20Paul%20Cousin/code.sql#L6

This is a good thought, you are trying to limit your query to the campaigns that brought people to the landing page. However, you are being too narrow in your focus. We want ALL the campaigns active for CoolTShirts, even those that returned users to the checkout page.

**Comment by pvcousin** [comment]
Yes, because that what campaigns do. The attract users to a website. My queries follow the user through the complete process of purchasing a t-shirt. All the purchases are included in my analysis of the four campaigns. Add up all the purchases for what you call seven campaigns and they will equal my total purchases for the four campaigns.
