### ISSUE TITLE
Again, you're missing retargeting campaigns

### ISSUE THREAD

**Issue by driskerr** [pvcousin/sql-scratch-capstone-turn-in#5]
https://github.com/pvcousin/sql-scratch-capstone-turn-in/blob/ea224748dad4b1e8b4a7bdd3c70ae0c5a259135f/SQL%20Project%20Paul%20Cousin/code.sql#L64-L82

Instead of running on `last_touch`, you joined with `first_touch` which eliminated retargeting campaigns from your analysis.

**Comment by pvcousin** [comment]
Actually, this query joins what you call retargeting campaigns to the users. So instead of following campaigns, I followed users. Marketing people want to know how people react to certain things. So we brought people to the website for the first time (landing). What happened then? When did they drop out (last touch)? Did they purchase? What percentage of people purchased compared to landing, shopping and checkout?
